/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.antithesis.ffi.internal;

public class FfiWrapper {
  public static long fuzz_get_random() {
    return FfiWrapperJNI.fuzz_get_random();
  }

  public static void fuzz_json_data(String message, long length) {
    FfiWrapperJNI.fuzz_json_data(message, length);
  }

  public static void fuzz_flush() {
    FfiWrapperJNI.fuzz_flush();
  }

  public static long init_coverage_module(long edgeCount, String symbolFilePath) {
    return FfiWrapperJNI.init_coverage_module(edgeCount, symbolFilePath);
  }

  public static boolean notify_coverage(long edgePlusModule) {
    return FfiWrapperJNI.notify_coverage(edgePlusModule);
  }

}
